"""Catalog of selectable diagnoses for the "Add Patient" form.

Each entry bundles everything needed to create a fully consistent record
across all 5 provider databases (GP, ED, Lab, Radiology, Pharmacy) for a
newly added patient, mirroring how the original seed data keeps GP code,
ICD-10, LOINC, SNOMED and RxNorm values in sync for the same diagnosis.
"""

DIAGNOSIS_CATALOG = [
    {
        "key": "chest_pain_exertion",
        "label": "Cardiology — Chest pain with exertion (CP-01)",
        "department": "Cardiology",
        "gp_code": "CP-01", "gp_text": "Chest pain with exertion",
        "icd10_code": "I20.0", "icd10_text": "Unstable angina",
        "physician": "Dr. Samira Nasser",
        "loinc_code": "10839-9", "test_name": "Troponin I",
        "result_value": "0.08", "unit": "ng/mL", "reference_range": "<0.04",
        "modality": "CR", "snomed_proc": "399208008", "proc_name": "Plain chest X-ray",
        "report": "Cardiomegaly with mild pulmonary vascular congestion. No pneumothorax.",
        "rxnorm": "1191", "drug": "Aspirin", "dose": "75 mg", "frequency": "Once daily",
    },
    {
        "key": "chest_tightness_rest",
        "label": "Cardiology — Chest tightness at rest (CP-02)",
        "department": "Cardiology",
        "gp_code": "CP-02", "gp_text": "Chest tightness at rest",
        "icd10_code": "I20.9", "icd10_text": "Angina pectoris, unspecified",
        "physician": "Dr. Khalid Mansour",
        "loinc_code": "718-7", "test_name": "Hemoglobin",
        "result_value": "11.2", "unit": "g/dL", "reference_range": "13.5-17.5",
        "modality": "CR", "snomed_proc": "399208008", "proc_name": "Plain chest X-ray",
        "report": "Mild cardiomegaly. Clear lung fields. No pleural effusion.",
        "rxnorm": "56795", "drug": "Nitroglycerin", "dose": "0.4 mg", "frequency": "Sublingual PRN chest pain",
    },
    {
        "key": "sob_chest_pain",
        "label": "Cardiology — Shortness of breath + chest pain (CP-03)",
        "department": "Cardiology",
        "gp_code": "CP-03", "gp_text": "Shortness of breath + chest pain",
        "icd10_code": "I50.9", "icd10_text": "Heart failure, unspecified",
        "physician": "Dr. Samira Nasser",
        "loinc_code": "2093-3", "test_name": "Total Cholesterol",
        "result_value": "245", "unit": "mg/dL", "reference_range": "<200",
        "modality": "CT", "snomed_proc": "77477000", "proc_name": "CT of thorax",
        "report": "No pulmonary embolism. Mild pericardial thickening noted.",
        "rxnorm": "203150", "drug": "Lisinopril", "dose": "10 mg", "frequency": "Once daily",
    },
    {
        "key": "hypertension",
        "label": "Cardiology — Hypertension uncontrolled (HT-01)",
        "department": "Cardiology",
        "gp_code": "HT-01", "gp_text": "Hypertension uncontrolled",
        "icd10_code": "I10", "icd10_text": "Essential hypertension",
        "physician": "Dr. Khalid Mansour",
        "loinc_code": "2160-0", "test_name": "Creatinine",
        "result_value": "1.1", "unit": "mg/dL", "reference_range": "0.7-1.2",
        "modality": "CR", "snomed_proc": "399208008", "proc_name": "Plain chest X-ray",
        "report": "Normal cardiac silhouette. Mild aortic calcification.",
        "rxnorm": "203150", "drug": "Lisinopril", "dose": "10 mg", "frequency": "Once daily",
    },
    {
        "key": "palpitations",
        "label": "Cardiology — Palpitations and chest discomfort (CP-04)",
        "department": "Cardiology",
        "gp_code": "CP-04", "gp_text": "Palpitations and chest discomfort",
        "icd10_code": "I47.9", "icd10_text": "Paroxysmal tachycardia, unspecified",
        "physician": "Dr. Samira Nasser",
        "loinc_code": "6690-2", "test_name": "WBC",
        "result_value": "11.5", "unit": "10^3/uL", "reference_range": "4.5-11.0",
        "modality": "CR", "snomed_proc": "399208008", "proc_name": "Plain chest X-ray",
        "report": "Enlarged mediastinum. Recommend cardiac MRI for further evaluation.",
        "rxnorm": "321064", "drug": "Metoprolol", "dose": "50 mg", "frequency": "Twice daily",
    },
    {
        "key": "chest_pain_radiating",
        "label": "Cardiology — Chest pain radiating to left arm (CP-05)",
        "department": "Cardiology",
        "gp_code": "CP-05", "gp_text": "Chest pain radiating to left arm",
        "icd10_code": "I21.9", "icd10_text": "Acute myocardial infarction, unspecified",
        "physician": "Dr. Khalid Mansour",
        "loinc_code": "2823-3", "test_name": "Potassium",
        "result_value": "3.4", "unit": "mEq/L", "reference_range": "3.5-5.0",
        "modality": "CR", "snomed_proc": "399208008", "proc_name": "Plain chest X-ray",
        "report": "Borderline cardiomegaly. No acute infiltrates.",
        "rxnorm": "308460", "drug": "Clopidogrel", "dose": "75 mg", "frequency": "Once daily",
    },
    {
        "key": "pneumonia",
        "label": "Respiratory Medicine — Productive cough with fever (RESP-01)",
        "department": "Respiratory Medicine",
        "gp_code": "RESP-01", "gp_text": "Productive cough with fever",
        "icd10_code": "J18.9", "icd10_text": "Pneumonia, unspecified organism",
        "physician": "Dr. Layla Haddad",
        "loinc_code": "6690-2", "test_name": "WBC",
        "result_value": "14.2", "unit": "10^3/uL", "reference_range": "4.5-11.0",
        "modality": "CR", "snomed_proc": "399208008", "proc_name": "Plain chest X-ray",
        "report": "Right lower lobe consolidation consistent with pneumonia.",
        "rxnorm": "18631", "drug": "Azithromycin", "dose": "500 mg", "frequency": "Once daily for 3 days",
    },
    {
        "key": "appendicitis",
        "label": "General Surgery — Right lower quadrant abdominal pain (GI-01)",
        "department": "General Surgery",
        "gp_code": "GI-01", "gp_text": "Right lower quadrant abdominal pain",
        "icd10_code": "K35.80", "icd10_text": "Unspecified acute appendicitis",
        "physician": "Dr. Yousef Barakat",
        "loinc_code": "6690-2", "test_name": "WBC",
        "result_value": "15.8", "unit": "10^3/uL", "reference_range": "4.5-11.0",
        "modality": "CT", "snomed_proc": "169070000", "proc_name": "CT of abdomen and pelvis",
        "report": "Dilated, non-compressible appendix with periappendiceal fat stranding, consistent with acute appendicitis.",
        "rxnorm": "2193", "drug": "Ceftriaxone", "dose": "1 g", "frequency": "Intravenous once daily",
    },
    {
        "key": "diabetes",
        "label": "Endocrinology — Polyuria, polydipsia, fatigue (DM-01)",
        "department": "Endocrinology",
        "gp_code": "DM-01", "gp_text": "Polyuria, polydipsia, fatigue",
        "icd10_code": "E11.65", "icd10_text": "Type 2 diabetes mellitus with hyperglycemia",
        "physician": "Dr. Rana Saleh",
        "loinc_code": "2345-7", "test_name": "Glucose",
        "result_value": "310", "unit": "mg/dL", "reference_range": "70-100",
        "modality": "CR", "snomed_proc": "399208008", "proc_name": "Plain chest X-ray",
        "report": "No acute cardiopulmonary process. Unremarkable baseline study.",
        "rxnorm": "6809", "drug": "Metformin", "dose": "500 mg", "frequency": "Twice daily",
    },
]
